language: python
python:
  - "3.7-dev"
install:
  - pip install scrapy requests zenhan scrapy_splash
before_script:
  - echo 'Asia/Tokyo' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
script:
  - scrapy crawl items -t csv -o - > ./items.csv
  - echo https://github.com/KeikaChan/prichan-items-scraper/releases/download/$TRAVIS_JOB_NUMBER/items.csv > items_url
before_deploy:
  - export TRAVIS_TAG=$TRAVIS_JOB_NUMBER 
  - export RELEASE_TITLE="Travis Auto Update $(date '+%Y%m%d%H%M%S')-$TRAVIS_JOB_NUMBER"
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/deploy.key\n" >> ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_1b0b4ad06c6e_key -iv $encrypted_1b0b4ad06c6e_iv -in ./.travis/prichan.enc -out deploy.key -d
  - mv deploy.key ~/.ssh/
  - chmod 600 ~/.ssh/deploy.key
  - git config --global user.email "devs@outlook.jp"
  - git config --global user.name "keykachan"
  - git clone git@github.com:KeikaChan/prichan-items-scraper.git
  - cd ./prichan-items-scraper
  - mv ../items_url ./
  - git add items_url
  - git tag -a $TRAVIS_JOB_NUMBER -m "result of $TRAVIS_JOB_NUMBER"
  - git commit -m "Travis Auto Update $TRAVIS_JOB_NUMBER https://travis-ci.org/KeikaChan/prichan-items-scraper/builds/$TRAVIS_BUILD_ID [skip ci]"
  - git push origin master --tags
  - cd ../
deploy:
  provider: releases
  name: $RELEASE_TITLE
  skip_cleanup: true
  api_key:
    secure: "lS6ftNCxBOgC2MXybs6Yq0pIfqDarACmjgWzhXAWklG2/8MvCXCRpJJc0/P3uFtlwagC3RotdnaZuriFqP4E3NVMnCdiGWvTAnNFtSRCVRKOxjPXRChOyZKoC39U1rBHGrD1GXyIfSE7V2Afyq91TqnvyyPhP4Q+VLplrdHUd/B1vPlCR2vDCHHJLZaoflgSnMuu5oba4fZRvWl62MfuwqqRoG061wu2fhD8P6sEfzqbna8mwTHTn/csF3Xl+CM/90x17UoSz4bFq5k+oVtA628odF5XT6tCq7szhRFf7VppkoKux7Pu7k7coGBRf7neDpxXXirs8wm24XEtWoB3LIP270QDHdpwaEMSZbrNT4yaNk9AR+nSLlQ4gzH0Gy5RLCxDAN+ao9TBiEzBhRtt+QnTA8IpnfoZOJgb7ldyVEphDpIc7L3MSSTiy2oMiEOZUYNYjZXeOpQ1FxJxfBQiLRmGaY/Bq+ewnsDQL/JFndtdyvskJ8oiDiM67Ou5r3ThW40RnMom4U6PfaCRQ2Jrop5e4DZNFb8ZyGfzIG5Yq1YCgQArMy1/Uw35zoPe+P+yJ1Jjdv5FukJVPdW6X7wQ1gMgnhyidLfepyffyDA/shFEhhQ8bWDIA8wDJ0Q+nyXRpAU8wsLjFPMVt6dU8HvnYMJg0ACQk9BqyPDvWYWpLFg="
  file:
    - items.csv
  on:
    branch: master
branches:
  only:
    - master
notifications:
  email: false
env:
  global:
    secure: "du4UsGazICmmuAQv1Lk6bX9GixlxfsBS1tVPgC+BjXSZ4rPj6shp5ucihAWMnk2FUbjNDLGHoJK2KtG9+hBOToddBMOaadTKw5Y1MkVT1D9w9LwF6ItqCT/OdO5OHKzBZNMsHze+oqjBqg+QknTqbaJ1tNaWXmSACzbWPRROUGFoCU3P2/Wc1rlkgnfM672OYjrN1HRybvy4BaKt5FxUUMsijJhwKEh9WtAc6e1YHTaN/TtK46csg6EvwC998hrENkKQlN9KqwlliplkwcUH/7FHdrQZh2App3nHXN1KhAgQDZFgqmj9s+Q0QJ24ZTNmkiXz0lUNtujyF6xoMzopLmQYE7jfxeikJpiiu/MOflXW3sDgNF2RAJn1thelLjjR86+DHPtcITFEWMdGQvyP9eyUwVo32X2PFijtCcfqf0+5cxCn1BwTrIdJc/Mzb7eoabRUV+rw2JvTa8rmtxj7yX4H6JUEZxgXRP6fKnnmTbU4VZP69jzqzUzW5nhkazJcOj9RwbYzGrSZPE1jRQ1fbylh8lltyqv7xBt4ZdklsjBxwMK4X6QPJNmVmIeB/gRff0Dgpqo4bKDvNfZE2whf7rTi+NISA15JmLr6AY+rxvAZ7tdsf1xOdjVi20nOts/lVGSlkvV67vMy5MTlg1RXF1SnrjwRhksZr85dX0TTQys="